CREATE TABLE `Items` (
  `Item_ID` int NOT NULL COMMENT 'Internal ID',
  `Name` varchar(60) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Item Name',
  `Description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Description / Effects',
  `Details` text COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Details about the item and additional info that may be useful.',
  `Rarity` varchar(20) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Item Rarity',
  `Version` int NOT NULL COMMENT 'Version of the item''s effects',
  `Img_URL` text COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Image URL Link'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Content for Items';

--
-- Dumping data for table `Items`
--
INSERT INTO `Items` (`Item_ID`, `Name`, `Description`, `Details`, `Rarity`, `Version`, `Img_URL`) VALUES
(1, 'Elusive Antlers', 'Spawns orbs of energy nearby every 10 seconds (-10% per stack), granting 12% movement speed up to 3 (+3 per stack) times for 12 seconds.', 'Upon initial release, this item was considered to be one of the worst items, due to it being a less powerful Razorwire that only activated upon being hit by an enemy. Upon being reworked for the first time, it became a great movement speed item, so much that it outshined other items like Goat Hoof and Energy Drink. This resulted in the base movement speed being removed, and only coming from the orbs that spawn.', 'Common', 4, 'https://riskofrain2.wiki.gg/images/Elusive_Antlers.png?aa64d9'),
(2, 'Bolstering Lantern', 'Increase your attack speed by 10% (+3.5% per stack) for up to 3 (+1 per stack) enemies and allies within 20 meters.', 'The original version of this item functioned somewhat opposite to the Delicate Watch, where the player was rewarded for being at lower health with extra damage. The only issue is, you don\'t have one shot protection at lower health,  so it was simply a Delicate Watch clone that was harder to activate, maintain, and risky to get the bonus. The second iteration of this item was really strong, as it scaled in both attack speed and radius, and is now still somewhat decent with the current scaling of attack speed and buff stack count.', 'Common', 4, 'https://riskofrain2.wiki.gg/images/thumb/Bolstering_Lantern.png/64px-Bolstering_Lantern.png?d82bc6'),
(3, 'Chronic Expansion', 'Killing an enemy increases your damage by 3.5% (+1% per stack), up to 10 (+5 per stack), for 7 seconds. Dealing damage refreshes the timer.', 'While this item didn\'t change much numerically, it made it easier to maintain stacks of the Chronic Expansion buff. Before, you had to kill enemies to maintain the buff, which became much harder to do in unique boss fights. Now, attacking an enemy can maintain those damage stacks, which is a really nice change.', 'Common', 2, 'https://riskofrain2.wiki.gg/images/thumb/Chronic_Expansion.png/64px-Chronic_Expansion.png?9c8581'),
(4, 'Warped Echo', 'The next source of damage is reduced by 10% and spread into 3 (+1 per stack) hits. All echoed damage is not lethal except the final hit. Recharges every 15 seconds.', 'Initially, the use of this item seemed fairly strange, and potentially dangerous if it cancels the player\'s one shot protection, and that it did. While it allows items like Medkit to activate in-between instances of damage, it could very well not be enough to be useful. Upon being reworked, this item was extremely powerful, especially in Eclipse, given the 30% damage reduction. The iteration we have now is still good, but nothing like it used to be, as synergies with Razorwire and Planula are no longer possible.', 'Common', 4, 'https://riskofrain2.wiki.gg/images/thumb/Warped_Echo.png/64px-Warped_Echo.png?e44c87'),
(5, 'Breaching Fin', 'Grounded enemies hit with any skill are launched and stunned. Enemies hit while airborne are launched again up to 2 times (+1 per stack). Launched enemies take increased damage by 10% from all sources per launch.', 'What was originally a mediocre white item with a strange effect, is now a fairly good damage source and utility for players. The stun can apply to bosses like False Son and Mithrix, which can prove to be extra useful given the damage increase per launch. One downside can be activating the launches and an area of effect item like Kjaro\'s Band at the same time, as the launches will take the target away from the damage source.', 'Uncommon', 3, 'https://riskofrain2.wiki.gg/images/thumb/Breaching_Fin.png/64px-Breaching_Fin.png?31f153'),
(6, 'Chance Doll', '40% (+10% per stack) chance to get higher rarity items from chance shrines on success.', 'Remaining unchanged from release, Chance Doll is surprisingly useful, and can allow players to even get yellow items from Shrines of Chance. This is one of the new items that promotes \'Macro Gameplay\', as players can wait to activate any chance shrines until they have cleared the stage for any potential Chance Dolls.', 'Uncommon', 1, 'https://riskofrain2.wiki.gg/images/thumb/Chance_Doll.png/64px-Chance_Doll.png?266327'),
(7, 'Luminous Shot', 'Activating your Secondary skill stores up to 5 charges (+1 per stack). Requires 3 charges for your Primary skill to fire lightning strikes, dealing 175% TOTAL damage (+50% per stack) each. Reduces Secondary skill cooldown by 20%.', 'The functionality of this item remains the same from its initial version, but is more consistent with its damage, given the requirement of 3 charges to activate, rather than activating at any amount of charges.', 'Uncommon', 2, 'https://riskofrain2.wiki.gg/images/thumb/Luminous_Shot.png/64px-Luminous_Shot.png?61489b'),
(8, 'Noxious Thorn', 'Gain 10% chance to bleed an enemy. Killing an enemy transfers 33% of every debuff stack to 1 enemy (+1 per stack) in a 20 meter radius (+5 meters per stack).', 'What started as a worse Razorwire (I\'m starting to see a theme here...) with bleed being applied to enemies turned into one of the greatest area of effect items to exist in the game. A 20 meter radius is a surprisingly large area to cover, and given that the Noxious Thorn will always transfer a debuff, only 33% of the stacks, this can be extremely useful and transfer hard-to-get debuffs like Deathmark.', 'Uncommon', 2, 'https://riskofrain2.wiki.gg/images/thumb/Noxious_Thorn.png/64px-Noxious_Thorn.png?db89f6'),
(9, 'Prayer Beads', 'Grows by gaining experience, storing 20% (+5% per stack) bonus stats. On removal, gain all stored stats.', 'This item only got some visual polish throughout the updates for Seeker\'s of the Storm, but also received an unintentional bug fix. Upon release, 3D printers could contain Prayer Beads, and given that the item grants additional stats once removed, players could infinitely increase their stats when seeing this printer present. There are also some interesting ways to activate the Prayer Beads effect, including having the item stolen by a Solus Extractor.', 'Uncommon', 1, 'https://riskofrain2.wiki.gg/images/thumb/Prayer_Beads.png/64px-Prayer_Beads.png?742784'),
(10, 'Sale Star', 'Gain an extra item on the first chest opened per stage. Each stack increases the chance of getting more items by 5%.', 'Another unchanged item from initial release, Sale Star is another macro item, if not the strongest one out of the bunch. The effect allows players to choose what chest they want to receive multiple items from, and can be useful on stages where legendary chests are present. Not to mention, using the Sale Star consumes it, so if a player already has a consumed one in their inventory, picking up another one will guarantee the extra item drop, rather than the 5% chance increase for an additional item.', 'Uncommon', 1, 'https://riskofrain2.wiki.gg/images/thumb/Sale_Star.png/64px-Sale_Star.png?a865b9'),
(11, 'Unstable Transmitter', 'Falling below 25% max health grants 60% of your max health as barrier. Gain an aura for 8 seconds that bleeds and teleports away enemies. Enemies killed by the aura extend the duration by 1 second. Consumed on use, regenerates at the beginning of each stage, and is used before Power Elixir and Delicate Watch.', 'Unstable Transmitter was probably the item that saw the lowest of the lows, and the highest highs throughout its iterations. Initially, it was considered a hazard to have, as it frequently teleported players into monsters and got them killed. When being reworked, it acted as an extra life on a 45 second cooldown, that could stack. It also takes priority over other health threshold items, which can be extremely useful. It then got a reality check and had the one shot protection removed along with some changes to its barrier.', 'Uncommon', 4, 'https://riskofrain2.wiki.gg/images/thumb/Unstable_Transmitter.png/64px-Unstable_Transmitter.png?40c0e7'),
(12, 'Electric Boomerang', '15% chance to fire a boomerang that travels a distance before returning, dealing 120% damage (+120% per stack) and stunning all enemies. Deals an additional 42% (+42% per stack) per second. Can strike enemies on the way back.', 'The Electric Boomerang didn\'t receive any gameplay changes throughout updates, but did have an issue where it always applied bleed to enemies while the player had the Sawmerang equipment. Given the higher fire rate of this item, it is surprisingly strong, especially with the ability to hit enemies on the return trip back.', 'Legendary', 2, 'https://riskofrain2.wiki.gg/images/thumb/Electric_Boomerang.png/64px-Electric_Boomerang.png?805d33'),
(13, 'Growth Nectar', 'Grants 4% increase to all stats for each buff, for a maximum of 4 buffs (+4 per stack).', 'Similar to Chronic Expansion, this item was \'balanced\', by being hard to maintain / achieve, but providing a strong buff. With additional stacks increasing the buff increase, this item became very strong very quickly, but heavily depended on the player\'s items. Now, it is a bit more balanced, but the stat increase is not as great as it seems, as it applies multiplicatively, and not additively.', 'Legendary', 3, 'https://riskofrain2.wiki.gg/images/thumb/Growth_Nectar.png/64px-Growth_Nectar.png?15a6f2'),
(14, 'Runic Lens', '3% chance on hit to call a meteor, dealing 2000% base damage. Every 100% damage dealt increases activation chance by 3% (+3% per stack) and damage by 150% (+50% per stack).', 'While the stats on this item were fairly similar in both versions, the description was a bit confusing as to what the item actually did, and there was little to no visual effect upon the meteor triggering. That has since been changed, and Runic Lens is one of the stronger burst damage items, given the lowest damage it can do is 2000% base damage.', 'Legendary', 2, 'https://riskofrain2.wiki.gg/images/thumb/Runic_Lens.png/64px-Runic_Lens.png?c74f3e'),
(15, 'Sonorous Whispers', 'Large monsters drop an item upon death. All elites have a 5% (+1% per stack) chance to drop an item.', 'Arguably one of the strongest items in the game, Sonorous Whispers allows players to gather large amounts of items, especially later in the game, just by killing enemies. The 15% drop chance for elites was way to high given the quantity of elites, so it was rightfully reduced to 5%, and the scaling of this item is so terrible, it is only worth it to have 1.', 'Legendary', 2, 'https://riskofrain2.wiki.gg/images/thumb/Sonorous_Whispers.png/64px-Sonorous_Whispers.png?893de8'),
(16, 'War Bonds', 'During boss events, 5 missiles strike the boss, dealing 2.5% (+2.5% per stack) of the boss\' maximum health as damage. Gold gained before the boss event increases missile count up to 20 (+5 per stack). Gold requirement scales over time.', 'Upon release, this was a contender for worst red item in the game, even worse than Aegis. The 75 gold it granted wasn\'t correct, and was usually less than that, providing about 2 small chest\'s worth of gold. It got a very big makeover in the first update for this DLC, and turned into a quite powerful, but situational damage item. It\'s strength also comes in the form of being useful in boss fights, including final boss fights. ', 'Legendary', 4, 'https://riskofrain2.wiki.gg/images/thumb/War_Bonds.png/64px-War_Bonds.png?fb59ab'),
(17, 'Longstanding Solitude', 'Leveling up grants a free unlock for the next purchase (+1 per stack), but all gold is converted to experience. Gold costs are increased by 50% (+50% per stack)', 'While I don\'t have much experience with this item, it seems fairly strong paired with some of the new economy items in this DLC. Stacking it seems to be the best way to use this item, especially since there is a level cap of 99 in Risk of Rain 2.', 'Lunar', 2, 'https://riskofrain2.wiki.gg/images/thumb/Longstanding_Solitude.png/64px-Longstanding_Solitude.png?6a5cdc'),
(18, 'Seed of Life', 'Revive survivors upon activation. Dying while holding this equipment revives you. Upon revival, receive 3 seconds of invulnerability and consume the equipment', 'Fairly self explanatory, this item is like Dio\'s Best Friend if it were an equipment. It can be useful on Engineer with his turrets, and can be a good filler spot in case of emergencies. Upon use, it turns into the Seed of Life (Consumed), where it drops healing orbs on the ground, healing the player, which is more useful than most of the other consumable equipment items in the game.', 'Equipment', 1, 'https://riskofrain2.wiki.gg/images/thumb/Seed_of_Life.png/64px-Seed_of_Life.png?508e73');

--
-- Indexes for table `Items`
--
ALTER TABLE `Items`
  ADD PRIMARY KEY (`Item_ID`);

--
-- AUTO_INCREMENT for table `Items`
--
ALTER TABLE `Items`
  MODIFY `Item_ID` int NOT NULL AUTO_INCREMENT COMMENT 'Internal ID', AUTO_INCREMENT=19;
COMMIT;
